import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Open Subtitle',
   description: 'Generated by create next app',
}

interface Children {
   children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Children>) {
   return (
      <html lang="en" className="dark">
         <body
            className={`${inter.className} dark:bg-black dark:text-[#afafaf]`}
         >
            <Header />
            {children}
         </body>
      </html>
   )
}
